### PR TITLE
added arch=amd64 to avoid apt notification

### PR DESCRIPTION
**Pull request by sahapasci**

### CODE REVIEW

**Comment by vincentbernat** [comment]
Not sure why this is needed. What kind of notifications do you want to suppress? Some versions are available for other archs.

**Comment by sahapasci** [comment]
When I did apt update, It was like this 

`... stable InRelease' doesn't support architecture 'i386'`

**Comment by sahapasci** [comment]
When I did apt update, It was like this 

`... stable InRelease' doesn't support architecture 'i386'`

**Comment by vincentbernat** [comment]
It depends on the version, I cannot hard code the architecture in the instructions, otherwise this won't work for people with other archs. I don't see a solution to remove the warning (except for you to manually add what you propose). Sorry.

**Pull request closed without merging**
