### PR TITLE
Strenghten our shell scripts

### PR DESCRIPTION
**Pull request by szepeviktor**
1. Quote sources
2. Let's know what we are doing: move pipe sign to the beginning of the line
3. Remove stray `</option>`

### CODE REVIEW

**Comment by szepeviktor** [comment]
Should `&` be `&amp;` in HTML?

**Comment by vincentbernat** [comment]
Why pipe would be better at the beginning of a line instead of at the end. It's the first time I see this style. Quoting is not needed, why quote? Both those items are really a matter of taste.

For `&`, in HTML5, non-ambiguous ampersands are valid.

**Comment by szepeviktor** [comment]
> Both those items are really a matter of taste.

Do you know JSLint? If you do something without thinking about it you may prevent a lot of bugs.
An example is: quotes for everything in shell.
BTW Quotes delimit the echoed string visually.

If you must decide on where does pipe belong _stronger_, the previous command or the next one?
I think pipe rather belongs to the next command. Specially when you (a human) read the code.
See Pipelines at https://google.github.io/styleguide/shell.xml

> Generate this string (newline)
> Then pipe it into that command

The other way:

> Generate this string and pipe it into (newline, your eyes are moving, you may lose the meaning :) )
> That command

I think the 1st one sounds better, and two of these one-line signs `| \` blend together.

**Comment by szepeviktor** [comment]
But you may of course close this PR.

**Comment by vincentbernat** [comment]
First, I don't consider Google to be a reference for shell scripts. For example, they say bash and nothing else. I am from the ones that try to stick with POSIX bourne shell unless something fancy is needed, like arrays (and in this case, I would switch to zsh which is a far batter alternative to bash for scripting as its word splitting policy is easier to work with).

Moreover, this is about interactive commands. Many people will just copy/paste but if for some reason, some people are retyping the command, putting the pipe at the end has several advantages: it can't be mistaken for a continuation character that most shells are using in interactive mode and in case the backslash is forgotten, this still works in most shells.

Also, this is the first time I see this style. I suppose this is more inspired from JS where people like to put punctuation at the beginning of the line.

So, nack for the pipe stuff, I don't care about quoting or not the echo and I gladly keep the removal of the stray option tag.

**Comment by szepeviktor** [comment]
> For example, they say bash and nothing else.

I happen to be a bashist also.

**Pull request closed without merging**
